runtime: python27
api_version: 1
threadsafe: true

handlers:
# - url: /
#   static_files: templates/home.html
#   upload: templates/home.html
- url: /static
  static_dir: static/
- url: /.*
  script: portfolio.wsgi.application

libraries:
- name: django
  version: "1.11"
# - url: /(.*\.(gif|png|jpg))$
#   static_files: assets/\1
#   upload: assets/.*\.(gif|png|jpg)$
